---

- name: edit sysconfig
  lineinfile:
    path: "/home/{{ user.name }}/.bash_profile"
    regexp: "{{ item }}"
    line: "{{ item }}"
    create: yes
    state: present
  with_items: "{{ user.profile_lines }}"
